# Generated by Django 4.2.21 on 2025-05-25 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharialBillPartyName",
            fields=[
                ("partyNameId", models.AutoField(primary_key=True, serialize=False)),
                ("partyName", models.CharField(max_length=100)),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CharialBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalBill", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commissionPercentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("others", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "partyName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.charialbillpartyname",
                    ),
                ),
            ],
        ),
    ]
