# Generated by Django 4.2.21 on 2025-05-25 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharialDailyExpensesOtherExpensesName",
            fields=[
                (
                    "otherExpensesId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("otherExpensesName", models.CharField(max_length=100)),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CharialDailyExpensesWagesName",
            fields=[
                ("wagesNameId", models.AutoField(primary_key=True, serialize=False)),
                ("wagesName", models.CharField(max_length=100)),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CharialDailyExpenses",
            fields=[
                ("expenseId", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "expenseType",
                    models.CharField(
                        choices=[("wages", "Wages"), ("other", "Other")], max_length=10
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "otherExpensesName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.charialdailyexpensesotherexpensesname",
                    ),
                ),
                (
                    "wagesName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.charialdailyexpenseswagesname",
                    ),
                ),
            ],
        ),
    ]
