# Generated by Django 4.2.21 on 2025-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_charialdailyexpensesotherexpensesname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charialbillpartyname",
            name="partyName",
            field=models.CharField(
                error_messages={"unique": "This party name already exists!"},
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="charialdailyexpensesotherexpensesname",
            name="otherExpensesName",
            field=models.CharField(
                error_messages={"unique": "This expense name already exists!"},
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="charialdailyexpenseswagesname",
            name="wagesName",
            field=models.CharField(
                error_messages={"unique": "This wage name already exists!"},
                max_length=100,
                unique=True,
            ),
        ),
    ]
