# Generated by Django 4.2.21 on 2025-05-25 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_charialbillpartyname_partyname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharialTradeSeller",
            fields=[
                ("sellerId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "This seller name already exists!"},
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "pendingAmount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="CharialTrade",
            fields=[
                ("tradeId", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("todayPurchase", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amPayment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pmPayment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.charialtradeseller",
                    ),
                ),
            ],
        ),
    ]
