# Generated by Django 4.2.21 on 2025-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_charialtradeseller_charialtrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="charialtrade",
            name="new_pending",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="charialtrade",
            name="pprevious_pending",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
    ]
