# Generated by Django 4.2.21 on 2025-06-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_charialtrade_new_pending_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharialBalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "britty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
