# Generated by Django 4.2.21 on 2025-06-01 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_charialbalancesheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="MahisgoatBalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "bill",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "britty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MahisgoatBillPartyName",
            fields=[
                ("partyNameId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "partyName",
                    models.CharField(
                        error_messages={"unique": "This party name already exists!"},
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="MahisgoatDailyExpensesOtherExpensesName",
            fields=[
                (
                    "otherExpensesId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "otherExpensesName",
                    models.CharField(
                        error_messages={"unique": "This expense name already exists!"},
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="MahisgoatDailyExpensesWagesName",
            fields=[
                ("wagesNameId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wagesName",
                    models.CharField(
                        error_messages={"unique": "This wage name already exists!"},
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="MahisgoatTradeSeller",
            fields=[
                ("sellerId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "This seller name already exists!"},
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "pendingAmount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dateAdded", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="MahisgoatTrade",
            fields=[
                ("tradeId", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("todayPurchase", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amPayment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pmPayment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "previous_pending",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=10
                    ),
                ),
                (
                    "new_pending",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=10
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.mahisgoattradeseller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MahisgoatDailyExpenses",
            fields=[
                ("expenseId", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "expenseType",
                    models.CharField(
                        choices=[("wages", "Wages"), ("other", "Other")], max_length=10
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "otherExpensesName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.mahisgoatdailyexpensesotherexpensesname",
                    ),
                ),
                (
                    "wagesName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.mahisgoatdailyexpenseswagesname",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MahisgoatBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalBill", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commissionPercentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("others", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "partyName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.mahisgoatbillpartyname",
                    ),
                ),
            ],
        ),
    ]
